/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/subscriptions": {
    /**
     * Returns every subscription owned by the caller, including
     * cancelled ones, together with the effective monthly JPY cost
     * computed by the backend.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"] & {
            data?: definitions["internal_api.ListSubscriptionsResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
      };
    };
    /**
     * Creates a subscription owned by the authenticated user.
     * The user_id is taken from the JWT, never from the body.
     */
    post: {
      parameters: {
        body: {
          /** subscription */
          body: definitions["internal_api.CreateSubscriptionRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"] & {
            data?: definitions["internal_api.SubscriptionDTO"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
      };
    };
  };
  "/subscriptions/{id}": {
    /** Full replacement update. Set status="cancelled" to soft-delete. */
    put: {
      parameters: {
        path: {
          /** subscription id (UUID) */
          id: string;
        };
        body: {
          /** subscription */
          body: definitions["internal_api.UpdateSubscriptionRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"] & {
            data?: definitions["internal_api.SubscriptionDTO"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
      };
    };
  };
  "/summary": {
    /**
     * Returns the effective monthly spend in JPY, a breakdown by
     * category for the pie chart, and a monthly trend for the
     * bar chart. All computations happen in Go with the fixed
     * FX rates configured on the backend.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"] & {
            data?: definitions["internal_api.SummaryResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
      };
    };
  };
  "/templates": {
    /**
     * Returns all pre-defined service templates (Netflix, Spotify,
     * etc.) with their plans nested inside. Consumed by the
     * "register from template" modal on the frontend.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"] & {
            data?: definitions["internal_api.ListTemplatesResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["github_com_syupii_cl_2_backend_internal_httpx.Response"];
        };
      };
    };
  };
}

export interface definitions {
  "github_com_syupii_cl_2_backend_internal_httpx.Response": {
    data?: unknown;
    /** @example */
    error?: string;
    /** @example true */
    success?: boolean;
  };
  "internal_api.CategoryBreakdown": {
    /** @example 5290 */
    amount_jpy?: string;
    /** @example Entertainment */
    category?: string;
    /** @example 3 */
    count?: number;
  };
  "internal_api.CreateSubscriptionRequest": {
    /**
     * @example monthly
     * @enum {string}
     */
    billing_cycle?: "monthly" | "yearly" | "once";
    /** @example Entertainment */
    category?: string;
    /** @example JPY */
    currency?: string;
    /** @example 2026-05-01 */
    next_billing_date?: string;
    /** @example 家族プラン */
    notes?: string;
    /** @example Visa ****1234 */
    payment_method?: string;
    /** @example Premium */
    plan_name?: string;
    /** @example 2290 */
    price?: string;
    /** @example Netflix */
    service_name?: string;
  };
  "internal_api.ListSubscriptionsResponse": {
    subscriptions?: definitions["internal_api.SubscriptionDTO"][];
  };
  "internal_api.ListTemplatesResponse": {
    templates?: definitions["internal_api.TemplateDTO"][];
  };
  "internal_api.MonthlyTrendPoint": {
    /** @example 7680 */
    amount_jpy?: string;
    /** @example 2026-04 */
    month?: string;
  };
  "internal_api.PlanDTO": {
    /**
     * @example monthly
     * @enum {string}
     */
    billing_cycle?: "monthly" | "yearly" | "once";
    /** @example JPY */
    currency?: string;
    /** @example 2290 */
    default_price?: string;
    /** @example 5f0b34c0-0ccd-4b9b-9b29-77a6c61b0123 */
    id?: string;
    /** @example Premium */
    plan_name?: string;
  };
  "internal_api.SubscriptionDTO": {
    /**
     * @example monthly
     * @enum {string}
     */
    billing_cycle?: "monthly" | "yearly" | "once";
    /** @example Entertainment */
    category?: string;
    /** @example 2026-04-01T10:00:00Z */
    created_at?: string;
    /** @example JPY */
    currency?: string;
    /** @example 3d49e7a3-4a2a-4b8e-9f3b-6f3b0d8e9c1a */
    id?: string;
    /**
     * @description MonthlyCostJPY is the effective monthly burden after converting to JPY
     * and dividing yearly prices by 12. Frontend can sum these safely.
     * @example 2290
     */
    monthly_cost_jpy?: string;
    /** @example 2026-05-01 */
    next_billing_date?: string;
    /** @example 家族プラン */
    notes?: string;
    /** @example Visa ****1234 */
    payment_method?: string;
    /** @example Premium */
    plan_name?: string;
    /** @example 2290 */
    price?: string;
    /** @example Netflix */
    service_name?: string;
    /**
     * @example active
     * @enum {string}
     */
    status?: "active" | "cancelled";
    /** @example 2026-04-01T10:00:00Z */
    updated_at?: string;
  };
  "internal_api.SummaryResponse": {
    /** @example 5 */
    active_count?: number;
    category_breakdown?: definitions["internal_api.CategoryBreakdown"][];
    /** @example JPY */
    currency?: string;
    monthly_trend?: definitions["internal_api.MonthlyTrendPoint"][];
    /** @example 5000 */
    once_total_jpy?: string;
    /** @example 7680 */
    total_monthly_jpy?: string;
  };
  "internal_api.TemplateDTO": {
    /** @example https://example.com/netflix.png */
    icon_url?: string;
    /** @example 26c8c2b0-4e6c-42c5-9a55-cfb0d4f6eb44 */
    id?: string;
    /** @example Netflix */
    name?: string;
    plans?: definitions["internal_api.PlanDTO"][];
  };
  "internal_api.UpdateSubscriptionRequest": {
    /**
     * @example monthly
     * @enum {string}
     */
    billing_cycle?: "monthly" | "yearly" | "once";
    /** @example Entertainment */
    category?: string;
    /** @example JPY */
    currency?: string;
    /** @example 2026-05-01 */
    next_billing_date?: string;
    /** @example 家族プラン */
    notes?: string;
    /** @example Visa ****1234 */
    payment_method?: string;
    /** @example Premium */
    plan_name?: string;
    /** @example 2290 */
    price?: string;
    /** @example Netflix */
    service_name?: string;
    /**
     * @example active
     * @enum {string}
     */
    status?: "active" | "cancelled";
  };
}

export interface operations {}

export interface external {}
