// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Plans (tiers) belonging to a service_template row.
type ServicePlan struct {
	ID           uuid.UUID       `json:"id"`
	TemplateID   uuid.UUID       `json:"template_id"`
	PlanName     string          `json:"plan_name"`
	DefaultPrice decimal.Decimal `json:"default_price"`
	// Either "monthly" or "yearly".
	BillingCycle string `json:"billing_cycle"`
	// ISO 4217 3-letter currency code (JPY, USD, ...).
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

// Master list of popular subscription services (Netflix, Spotify, ...).
type ServiceTemplate struct {
	ID uuid.UUID `json:"id"`
	// Human-readable service name. Unique.
	Name string `json:"name"`
	// Publicly accessible logo image URL.
	IconUrl   pgtype.Text `json:"icon_url"`
	CreatedAt time.Time   `json:"created_at"`
}

// Payment method registered by a user (credit card, bank account, etc.).
type PaymentMethod struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

// Individual subscriptions owned by a Supabase auth user.
type UserSubscription struct {
	ID uuid.UUID `json:"id"`
	// Owner (Supabase auth.users.id). RLS restricts access to this user.
	UserID      uuid.UUID       `json:"user_id"`
	ServiceName string          `json:"service_name"`
	PlanName    pgtype.Text     `json:"plan_name"`
	Price       decimal.Decimal `json:"price"`
	Currency    string          `json:"currency"`
	// Either "monthly" or "yearly". yearly values are divided by 12 in summary.
	BillingCycle string `json:"billing_cycle"`
	// Next scheduled charge date.
	NextBillingDate time.Time   `json:"next_billing_date"`
	Category        pgtype.Text `json:"category"`
	PaymentMethod   pgtype.Text `json:"payment_method"`
	// Soft-deletion flag. "active" or "cancelled". We never DELETE rows.
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
