// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Payment methods CRUD.
	ListPaymentMethods(ctx context.Context, userID uuid.UUID) ([]PaymentMethod, error)
	CreatePaymentMethod(ctx context.Context, userID uuid.UUID, name string) (PaymentMethod, error)
	DeletePaymentMethod(ctx context.Context, id, userID uuid.UUID) error
	// Permanently delete a subscription row (hard delete).
	DeleteUserSubscription(ctx context.Context, arg DeleteUserSubscriptionParams) error
	// Convenience mutation for the "cancel" action in the UI. Equivalent to
	// UpdateUserSubscription with status='cancelled', but cheaper for the client.
	CancelUserSubscription(ctx context.Context, arg CancelUserSubscriptionParams) (UserSubscription, error)
	// Insert a new subscription. user_id is always set from the JWT claim, never
	// from the request body, so the INSERT policy's WITH CHECK passes. The
	// handler is responsible for passing a valid status ('active' or 'cancelled').
	CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) (UserSubscription, error)
	// Fetch one subscription by its primary key, scoped to the caller.
	GetUserSubscription(ctx context.Context, arg GetUserSubscriptionParams) (UserSubscription, error)
	// Only the subscriptions currently charging the user. Used by GET /summary.
	ListActiveUserSubscriptions(ctx context.Context, userID uuid.UUID) ([]UserSubscription, error)
	// Returns every plan across all templates. Used by the API /templates endpoint
	// to build the nested template -> plans response in a single round trip.
	ListAllServicePlans(ctx context.Context) ([]ServicePlan, error)
	// Returns every plan attached to a given template, cheapest first.
	ListServicePlansByTemplate(ctx context.Context, templateID uuid.UUID) ([]ServicePlan, error)
	// =============================================================================
	// Subscription Dashboard - SQL Queries (consumed by sqlc)
	// =============================================================================
	// All queries are executed through the backend API, which authenticates the
	// caller via Supabase JWT and then runs SQL with the user's own Postgres role
	// so that Row-Level Security (schema.sql) is applied automatically.
	//
	// Naming convention:
	//   :one      -> exactly one row
	//   :many     -> a slice of rows
	//   :exec     -> no result set
	// =============================================================================
	// =============================================================================
	// service_templates / service_plans (read-only master data)
	// =============================================================================
	// Returns all well-known service templates, ordered by name.
	ListServiceTemplates(ctx context.Context) ([]ServiceTemplate, error)
	// =============================================================================
	// user_subscriptions : CRUD for the authenticated user
	// =============================================================================
	// All subscriptions belonging to the given user, regardless of status.
	// The explicit user_id filter is defense-in-depth; RLS already enforces it.
	ListUserSubscriptions(ctx context.Context, userID uuid.UUID) ([]UserSubscription, error)
	// =============================================================================
	// Aggregations for GET /summary
	// =============================================================================
	// NOTE: Currency conversion (USD->JPY) and yearly->monthly normalisation live
	// in Go, not in SQL. The queries below return per-row raw values in the
	// currency the user entered. The handler normalises and sums them.
	// Category-level breakdown for the pie chart. We keep rows split by currency
	// and billing_cycle so the Go layer can apply the correct conversion factor.
	SumActiveSubscriptionsByCategory(ctx context.Context, userID uuid.UUID) ([]SumActiveSubscriptionsByCategoryRow, error)
	// Returns the raw charges that fall inside each of the most recent N months,
	// grouped by the billing month. This powers the monthly trend bar chart.
	// $1 = user_id, $2 = number of months to look back (inclusive of current).
	SumActiveSubscriptionsByMonth(ctx context.Context, arg SumActiveSubscriptionsByMonthParams) ([]SumActiveSubscriptionsByMonthRow, error)
	// Full update (PUT /subscriptions/:id). Callers must send the complete object.
	// status can be flipped between 'active' and 'cancelled' here (soft-delete).
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error)
}

var _ Querier = (*Queries)(nil)
