// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cancelUserSubscription = `-- name: CancelUserSubscription :one
UPDATE public.user_subscriptions
SET status = 'cancelled'
WHERE id = $1
  AND user_id = $2
RETURNING
    id,
    user_id,
    service_name,
    plan_name,
    price,
    currency,
    billing_cycle,
    next_billing_date,
    category,
    payment_method,
    status,
    created_at,
    updated_at
`

type CancelUserSubscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Convenience mutation for the "cancel" action in the UI. Equivalent to
// UpdateUserSubscription with status='cancelled', but cheaper for the client.
func (q *Queries) CancelUserSubscription(ctx context.Context, arg CancelUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, cancelUserSubscription, arg.ID, arg.UserID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.PlanName,
		&i.Price,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.Category,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSubscription = `-- name: CreateUserSubscription :one
INSERT INTO public.user_subscriptions (
    user_id,
    service_name,
    plan_name,
    price,
    currency,
    billing_cycle,
    next_billing_date,
    category,
    payment_method,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING
    id,
    user_id,
    service_name,
    plan_name,
    price,
    currency,
    billing_cycle,
    next_billing_date,
    category,
    payment_method,
    status,
    created_at,
    updated_at
`

type CreateUserSubscriptionParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	ServiceName     string          `json:"service_name"`
	PlanName        pgtype.Text     `json:"plan_name"`
	Price           decimal.Decimal `json:"price"`
	Currency        string          `json:"currency"`
	BillingCycle    string          `json:"billing_cycle"`
	NextBillingDate time.Time       `json:"next_billing_date"`
	Category        pgtype.Text     `json:"category"`
	PaymentMethod   pgtype.Text     `json:"payment_method"`
	Status          string          `json:"status"`
}

// Insert a new subscription. user_id is always set from the JWT claim, never
// from the request body, so the INSERT policy's WITH CHECK passes. The
// handler is responsible for passing a valid status ('active' or 'cancelled').
func (q *Queries) CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, createUserSubscription,
		arg.UserID,
		arg.ServiceName,
		arg.PlanName,
		arg.Price,
		arg.Currency,
		arg.BillingCycle,
		arg.NextBillingDate,
		arg.Category,
		arg.PaymentMethod,
		arg.Status,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.PlanName,
		&i.Price,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.Category,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT
    id,
    user_id,
    service_name,
    plan_name,
    price,
    currency,
    billing_cycle,
    next_billing_date,
    category,
    payment_method,
    status,
    created_at,
    updated_at
FROM public.user_subscriptions
WHERE id = $1
  AND user_id = $2
`

type GetUserSubscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Fetch one subscription by its primary key, scoped to the caller.
func (q *Queries) GetUserSubscription(ctx context.Context, arg GetUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscription, arg.ID, arg.UserID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.PlanName,
		&i.Price,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.Category,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUserSubscriptions = `-- name: ListActiveUserSubscriptions :many
SELECT
    id,
    user_id,
    service_name,
    plan_name,
    price,
    currency,
    billing_cycle,
    next_billing_date,
    category,
    payment_method,
    status,
    created_at,
    updated_at
FROM public.user_subscriptions
WHERE user_id = $1
  AND status = 'active'
ORDER BY next_billing_date ASC
`

// Only the subscriptions currently charging the user. Used by GET /summary.
func (q *Queries) ListActiveUserSubscriptions(ctx context.Context, userID uuid.UUID) ([]UserSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSubscription{}
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.PlanName,
			&i.Price,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.Category,
			&i.PaymentMethod,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllServicePlans = `-- name: ListAllServicePlans :many
SELECT
    id,
    template_id,
    plan_name,
    default_price,
    billing_cycle,
    currency,
    created_at
FROM public.service_plans
ORDER BY template_id ASC, default_price ASC
`

// Returns every plan across all templates. Used by the API /templates endpoint
// to build the nested template -> plans response in a single round trip.
func (q *Queries) ListAllServicePlans(ctx context.Context) ([]ServicePlan, error) {
	rows, err := q.db.Query(ctx, listAllServicePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServicePlan{}
	for rows.Next() {
		var i ServicePlan
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.PlanName,
			&i.DefaultPrice,
			&i.BillingCycle,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePlansByTemplate = `-- name: ListServicePlansByTemplate :many
SELECT
    id,
    template_id,
    plan_name,
    default_price,
    billing_cycle,
    currency,
    created_at
FROM public.service_plans
WHERE template_id = $1
ORDER BY default_price ASC
`

// Returns every plan attached to a given template, cheapest first.
func (q *Queries) ListServicePlansByTemplate(ctx context.Context, templateID uuid.UUID) ([]ServicePlan, error) {
	rows, err := q.db.Query(ctx, listServicePlansByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServicePlan{}
	for rows.Next() {
		var i ServicePlan
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.PlanName,
			&i.DefaultPrice,
			&i.BillingCycle,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTemplates = `-- name: ListServiceTemplates :many



SELECT
    id,
    name,
    icon_url,
    created_at
FROM public.service_templates
ORDER BY name ASC
`

// =============================================================================
// Subscription Dashboard - SQL Queries (consumed by sqlc)
// =============================================================================
// All queries are executed through the backend API, which authenticates the
// caller via Supabase JWT and then runs SQL with the user's own Postgres role
// so that Row-Level Security (schema.sql) is applied automatically.
//
// Naming convention:
//
//	:one      -> exactly one row
//	:many     -> a slice of rows
//	:exec     -> no result set
//
// =============================================================================
// =============================================================================
// service_templates / service_plans (read-only master data)
// =============================================================================
// Returns all well-known service templates, ordered by name.
func (q *Queries) ListServiceTemplates(ctx context.Context) ([]ServiceTemplate, error) {
	rows, err := q.db.Query(ctx, listServiceTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceTemplate{}
	for rows.Next() {
		var i ServiceTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many

SELECT
    id,
    user_id,
    service_name,
    plan_name,
    price,
    currency,
    billing_cycle,
    next_billing_date,
    category,
    payment_method,
    status,
    created_at,
    updated_at
FROM public.user_subscriptions
WHERE user_id = $1
ORDER BY status ASC, next_billing_date ASC
`

// =============================================================================
// user_subscriptions : CRUD for the authenticated user
// =============================================================================
// All subscriptions belonging to the given user, regardless of status.
// The explicit user_id filter is defense-in-depth; RLS already enforces it.
func (q *Queries) ListUserSubscriptions(ctx context.Context, userID uuid.UUID) ([]UserSubscription, error) {
	rows, err := q.db.Query(ctx, listUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSubscription{}
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.PlanName,
			&i.Price,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.Category,
			&i.PaymentMethod,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumActiveSubscriptionsByCategory = `-- name: SumActiveSubscriptionsByCategory :many

SELECT
    COALESCE(category, 'Uncategorized') AS category,
    currency,
    billing_cycle,
    SUM(price)::NUMERIC(14, 2) AS total_price,
    COUNT(*)::BIGINT           AS subscription_count
FROM public.user_subscriptions
WHERE user_id = $1
  AND status = 'active'
GROUP BY category, currency, billing_cycle
ORDER BY category ASC
`

type SumActiveSubscriptionsByCategoryRow struct {
	Category          string          `json:"category"`
	Currency          string          `json:"currency"`
	BillingCycle      string          `json:"billing_cycle"`
	TotalPrice        decimal.Decimal `json:"total_price"`
	SubscriptionCount int64           `json:"subscription_count"`
}

// =============================================================================
// Aggregations for GET /summary
// =============================================================================
// NOTE: Currency conversion (USD->JPY) and yearly->monthly normalisation live
// in Go, not in SQL. The queries below return per-row raw values in the
// currency the user entered. The handler normalises and sums them.
// Category-level breakdown for the pie chart. We keep rows split by currency
// and billing_cycle so the Go layer can apply the correct conversion factor.
func (q *Queries) SumActiveSubscriptionsByCategory(ctx context.Context, userID uuid.UUID) ([]SumActiveSubscriptionsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, sumActiveSubscriptionsByCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumActiveSubscriptionsByCategoryRow{}
	for rows.Next() {
		var i SumActiveSubscriptionsByCategoryRow
		if err := rows.Scan(
			&i.Category,
			&i.Currency,
			&i.BillingCycle,
			&i.TotalPrice,
			&i.SubscriptionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumActiveSubscriptionsByMonth = `-- name: SumActiveSubscriptionsByMonth :many
SELECT
    date_trunc('month', next_billing_date)::DATE AS billing_month,
    currency,
    billing_cycle,
    SUM(price)::NUMERIC(14, 2) AS total_price,
    COUNT(*)::BIGINT           AS subscription_count
FROM public.user_subscriptions
WHERE user_id = $1
  AND status = 'active'
  AND next_billing_date >= (date_trunc('month', CURRENT_DATE) - (($2::INT - 1) || ' months')::INTERVAL)
GROUP BY billing_month, currency, billing_cycle
ORDER BY billing_month ASC
`

type SumActiveSubscriptionsByMonthParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 int32     `json:"column_2"`
}

type SumActiveSubscriptionsByMonthRow struct {
	BillingMonth      time.Time       `json:"billing_month"`
	Currency          string          `json:"currency"`
	BillingCycle      string          `json:"billing_cycle"`
	TotalPrice        decimal.Decimal `json:"total_price"`
	SubscriptionCount int64           `json:"subscription_count"`
}

// Returns the raw charges that fall inside each of the most recent N months,
// grouped by the billing month. This powers the monthly trend bar chart.
// $1 = user_id, $2 = number of months to look back (inclusive of current).
func (q *Queries) SumActiveSubscriptionsByMonth(ctx context.Context, arg SumActiveSubscriptionsByMonthParams) ([]SumActiveSubscriptionsByMonthRow, error) {
	rows, err := q.db.Query(ctx, sumActiveSubscriptionsByMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumActiveSubscriptionsByMonthRow{}
	for rows.Next() {
		var i SumActiveSubscriptionsByMonthRow
		if err := rows.Scan(
			&i.BillingMonth,
			&i.Currency,
			&i.BillingCycle,
			&i.TotalPrice,
			&i.SubscriptionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserSubscription = `-- name: UpdateUserSubscription :one
UPDATE public.user_subscriptions
SET
    service_name      = $3,
    plan_name         = $4,
    price             = $5,
    currency          = $6,
    billing_cycle     = $7,
    next_billing_date = $8,
    category          = $9,
    payment_method    = $10,
    status            = $11
WHERE id = $1
  AND user_id = $2
RETURNING
    id,
    user_id,
    service_name,
    plan_name,
    price,
    currency,
    billing_cycle,
    next_billing_date,
    category,
    payment_method,
    status,
    created_at,
    updated_at
`

type UpdateUserSubscriptionParams struct {
	ID              uuid.UUID       `json:"id"`
	UserID          uuid.UUID       `json:"user_id"`
	ServiceName     string          `json:"service_name"`
	PlanName        pgtype.Text     `json:"plan_name"`
	Price           decimal.Decimal `json:"price"`
	Currency        string          `json:"currency"`
	BillingCycle    string          `json:"billing_cycle"`
	NextBillingDate time.Time       `json:"next_billing_date"`
	Category        pgtype.Text     `json:"category"`
	PaymentMethod   pgtype.Text     `json:"payment_method"`
	Status          string          `json:"status"`
}

// Full update (PUT /subscriptions/:id). Callers must send the complete object.
// status can be flipped between 'active' and 'cancelled' here (soft-delete).
func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, updateUserSubscription,
		arg.ID,
		arg.UserID,
		arg.ServiceName,
		arg.PlanName,
		arg.Price,
		arg.Currency,
		arg.BillingCycle,
		arg.NextBillingDate,
		arg.Category,
		arg.PaymentMethod,
		arg.Status,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.PlanName,
		&i.Price,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.Category,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
